defaults: &defaults
  host: "activities.eurucamp.org"
  mailers:
    from: "activities@eurucamp.org"
  errors:
    from: "exception@eurucamp.org"
    to:
      - "piotr@gega.io"
      - "florian@polarblau.com"

development:
  <<: *defaults
  host: "localhost:3000"

test:
  <<: *defaults

staging:
  <<: *defaults
  host: "activities-staging.eurucamp.org"

production:
  <<: *defaults
