defaults: &defaults
  event:
    name: "rubyweek"
    start_time: 2015-07-27 00:00:00
    end_time: 2015-08-09 23:59:59
  host: "rubyweek.org"
  mailers:
    from: "activities@eurucamp.org"
  errors:
    from: "exception@eurucamp.org"
    to:
      - "cfp-errors@eurucamp.org"
  seo:
    title: "rubyweek"
    author: "eurucamp team"
    description: "List of events around eurucamp and JRubyConf"

development:
  <<: *defaults
  host: "activities.dev:3000"

test:
  <<: *defaults

staging:
  <<: *defaults
  host: "eurucamp-activities-staging.shellyapp.com"

production:
  <<: *defaults
